federation_version: =2.7.0
subgraphs:
  listings:
    routing_url: http://localhost:8080/graphql
    schema:
      file: ./listings/src/main/resources/schema/schema.graphqls
  reviews:
    routing_url: http://localhost:8090/graphql
    schema:
      file: ./reviews/src/main/resources/schema/schema.graphqls